version: '2'
services:
    db:
        image: postgres:9.6
        restart: always
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_DB=db
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - pg_data:/var/lib/postgresql/data/pgdata
    odoo:

        image: $ODOO_IMAGE:$ODOO_MINOR
        restart: always
        external_links:
            - aeroo:aeroo
        depends_on:
            - db
        ports:
            - "8069:8069"
            - "8072:8072"
            - "5678:5678"
        # sudo ifconfig lo0 alias 192.100.200.1/24    
        volumes:
            - ./data/custom/repositories:/home/odoo/custom/repositories
            - odoo_data:/opt/odoo/data
        env_file:
            - .env
        #these extra env items are for nginx-proxy automated reverse proxy
        #we need to design an automated hostname/dns subsystem 
        environment:
            - VIRTUAL_HOST=odoo0.local
            - VIRTUAL_PORT=8069


#dependency: nginx-proxy must be running before and must create this network
#networks:
#  default:
#    external:
#     name: dockernginxadhoc_backend

volumes:
    pg_data:
    odoo_data:
